default:
  image: docker:19.03.12

variables:

  IMAGE_NAME: demo
  CI_IMAGE: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
stages:
  - build
  - deploy
build:
  stage: build
  tags:
    - "dev"
  only:
    - master
  script:
    - docker build -t $CI_IMAGE -f ./Dockerfile .



deploy:
  stage: deploy
  tags:
    - "dev"
  only:
    - master
  script:
    - docker run -d  -v $(pwd):/demo  -p 8000:8000 $CI_IMAGE /bin/bash -c /demo/entrypoint.sh
